# -*- coding: utf-8 -*-
"""Slashmark_basic_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SReujFsjO7pIwuPUsVMH0mgvd82BRAuR
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

data=pd.read_csv("/content/kc_house_data.csv")

data

data.head()

data.describe()

data.shape

data.isnull().sum()

data['bedrooms'].value_counts().plot(kind='bar')
plt.title('number of Bedroom')
plt.xlabel('Bedrooms')
plt.ylabel('Count')
sns.despine

plt.scatter(data.floors,data.price)

plt.scatter(data.condition,data.price)

"""# ***Linear regression***"""

from sklearn.linear_model import LinearRegression

x=data.drop(['id', 'price','date'],axis=1)

x

y=data['price']

y

from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2,random_state =2)

model=LinearRegression()

model.fit(x_train,y_train)

model.score(x_test,y_test)

"""# ***Ensemble***"""

from sklearn import ensemble
clf = ensemble.GradientBoostingRegressor(n_estimators = 400, max_depth = 5, min_samples_split = 2,
          learning_rate = 0.1, loss = 'squared_error')

clf.fit(x_train, y_train)

clf.score(x_test,y_test)